language: python
python:
    - "2.7"

install: python -m pip install -r requirements.txt
env:
   - CONFIG_PATH=blog.config.TravisConfig
before_script:
   - psql -c 'create database "blogful-test";' -U postgres
   - psql -c 'create database "blogful";' -U postgres
script: 
    - PYTHONPATH=. python tests/test_filters.py
      # - PYTHONPATH=. python tests/test_views_integration.py
      #- PYTHONPATH=. python tests/test_views_acceptance.py
    # add any other tests here 
    # recommitting because it's not working
    #
